# Generated by Django 5.0.3 on 2024-04-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="catalog.product",
                verbose_name="продукт",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.PositiveIntegerField(verbose_name="Номер версии"),
        ),
    ]
